### ISSUE TITLE
Current status and future plans

### ISSUE THREAD

**Issue by toupeira** [playon/doorkeeper-openid_connect#17]
I'm looking into implementing OpenID Connect in GitLab and stumbled over this gem, as well as the lower-level [openid_connect](https://github.com/nov/openid_connect) Rack middleware. As GitLab already uses Doorkeeper this approach seems a lot more straight-forward, so I'm planning to first improve this gem a bit and have a few questions:

- What's the current status and your future plans, which areas need the most love?
- Do you have an overview of which parts of the [core spec](http://openid.net/specs/openid-connect-basic-1_0.html) are implemented?
- Have you tried the [conformance testing](http://openid.net/certification/testing/) with this library?

Thanks for your work!

**Comment by stephendyer** [comment]
Hi Markus,
The project is currently in maintenance mode. We still use the gem, but haven’t touched the code in over a year, and the original developer has left the company. If you’re interested in using the code, I’d recommend forking the project.

Thanks,
Steve Dyer

**Comment by toupeira** [comment]
@stephendyer ok thanks, I'll make a fork then!

@samdengler let me know if you have any plans or old notes :)

**Comment by toupeira** [comment]
@stephendyer I'm wondering if you would be ok with [transfering the project to the `doorkeeper-gem` organization](https://github.com/doorkeeper-gem/doorkeeper/issues/883), so we can keep issues etc.? To do this you would need to give @tute administrator access to the repository.

**Comment by stephendyer** [comment]
Hi Markus,
This shouldn’t be a problem. We just want to make sure any ts are crossed and is dotted. I’ll get back to you in a couple of days.

Thanks,
Steve

**Comment by toupeira** [comment]
@stephendyer sure no problem! I'll take care to keep all the attribution, and feel free to add a comment like "originally sponsored by PlayON!" to the README :-)

**Comment by stephendyer** [comment]
Hi Marcus,
Sorry for the delay, be we are ready to transfer the ownership. All we need is for you to agree to and send us an e-mail with something along the following lines:

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I acknowledge and agree as follows:
·         2080 Media, Inc. d/b/a PlayOn Sports is the original author of and holds the copyright in the Doorkeeper::OpenidConnect plugin.
·         PlayOn has released the plugin under the MIT License (as included in the License.txt file in the project repository).
·         As a condition of 2080 transferring control of the project’s repository to me, I will continue to release all modifications and future versions of the plugin under the same MIT License.
·         Additionally, I will require any person that takes over control of the repository to agree to these same terms.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Thanks,
Steve

**Comment by toupeira** [comment]
@stephendyer thanks these terms are fine with me, do you want me to send the mail to a specific address or is a comment here sufficient?

Also the current `LICENSE.txt` attributes the copyright to @samdengler directly, IANAL but you might want to clarify that with him as well ;-)

**Comment by stephendyer** [comment]
Please send the e-mail to Stephen.dyer@playonsports.com<mailto:Stephen.dyer@playonsports.com>

We’ll fix the License.txt file before transferring. Sam will be OK ;-)

Thanks,
Steve

**Comment by toupeira** [comment]
Ok great, I sent you the mail. To start the transfer, please add @tute (doorkeeper maintainer) as administrator to the repository, so he can move it to the doorkeeper-org organization.

**Comment by stephendyer** [comment]
We are all set to transfer. I just want to verify that @tute is Tute Costa?

**Comment by toupeira** [comment]
Yep, that's Tute Costa as on https://github.com/tute

**Comment by tute** [comment]
Thanks! I click on the invitation email, but GitHub says "that invitation doesn't exist". Would you send it again, please?

**Comment by stephendyer** [comment]
I’ve just added you. Please let me know if you don’t get the invite.

**Comment by tute** [comment]
Got it, thanks! Will add @toupeira tonight or this week.
